# Generated by Django 3.0.2 on 2020-01-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jqueryapp', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
