# Generated by Django 3.0.2 on 2020-01-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jqueryapp', '0003_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
