# Generated by Django 3.0.2 on 2020-01-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jqueryapp', '0004_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
